### ISSUE TITLE
Framebuffer Support

### ISSUE THREAD

**Issue by embetrix** [slint-ui/meta-slint#12]
Does Slint Build support only Frambuffer ? X11 or Wayland are way too ressource hungry for a small system

**Comment by tronical** [comment]
If your frame buffer offers GPU accelerated rendering with either Vulkan's KHR Display extension or rendering via EGL's `KHR_platform_gbm` extension, then you can use Slint without X11/Wayland by enabling the [LinuxKMS](https://slint.dev/releases/1.2.2/docs/slint/src/advanced/backend_linuxkms) backend.

Since you posted this in `meta-slint`, you can activate this feature if your'e using a Git build and activated the [`backend-linuxkms`](https://github.com/slint-ui/meta-slint#features) package config feature.

**Comment by embetrix** [comment]
and if I want to use only framebuffer without EGL and of course no X11/Wayland

**Comment by embetrix** [comment]
As I saw the documentation Slint does support MCU which does not have Graphic HW acceleration, this should be theoretically possible...

**Comment by tronical** [comment]
Yes, that should be theoretically possible. We're tracking support for pure software rendering via DUMB buffers for either Skia or Slint's software renderer in https://github.com/slint-ui/slint/issues/3390
